images:
  - dir: prow/cmd/admission
  - dir: prow/cmd/branchprotector
  - dir: prow/cmd/checkconfig
  - dir: prow/cmd/config-bootstrapper
  - dir: prow/cmd/deck
    arch: linux/amd64,linux/arm64
  - dir: prow/cmd/exporter
  - dir: prow/cmd/gerrit
  - dir: prow/cmd/crier
    arch: linux/amd64,linux/arm64
  - dir: prow/cmd/gangway
  - dir: prow/cmd/generic-autobumper
  - dir: prow/cmd/grandmatriarch
  - dir: prow/cmd/gcsupload
  - dir: prow/cmd/hook
    arch: linux/amd64,linux/arm64
  - dir: prow/cmd/hmac
  - dir: prow/cmd/horologium
    arch: linux/amd64,linux/arm64
  - dir: prow/cmd/invitations-accepter
  - dir: prow/cmd/jenkins-operator
  - dir: prow/cmd/mkpj
  - dir: prow/cmd/mkpod
  - dir: prow/cmd/peribolos
  - dir: prow/cmd/sinker
  - dir: prow/cmd/status-reconciler
    arch: linux/amd64,linux/arm64
  - dir: prow/cmd/sub
  - dir: prow/cmd/tide
    arch: linux/amd64,linux/arm64
  - dir: prow/cmd/tot
  - dir: prow/cmd/pipeline
  - dir: prow/cmd/prow-controller-manager
    arch: linux/amd64,linux/arm64
  - dir: prow/cmd/webhook-server
  # pod utils
  - dir: prow/cmd/clonerefs
    arch: all
  - dir: prow/cmd/entrypoint
    arch: all
  - dir: prow/cmd/initupload
    arch: all
  - dir: prow/cmd/sidecar
    arch: all
  - dir: prow/external-plugins/needs-rebase
  - dir: prow/external-plugins/cherrypicker
  - dir: prow/external-plugins/refresh
  - dir: ghproxy
    arch: linux/amd64,linux/arm64
  - dir: label_sync
  - dir: robots/commenter
  - dir: robots/pr-creator
  - dir: robots/issue-creator
  - dir: testgrid/cmd/configurator
  - dir: gcsweb/cmd/gcsweb
  - dir: gencred
  - dir: experiment/ml/analyze
